** Major overhaul, reverted back to bash shell given all of the complexities of zsh, and script's inability to record colors properly, rather it records the control characters that make the colors in interactive zsh's and it's therefore very hard to read/descipher the real commands from the color control patterns.

diff --git a/ctee b/ctee
--- a/ctee
+++ b/ctee
@@ -1,32 +1,19 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
+
+if [ "$(id -u)" = "0" ]; then
+    echo "[x] This script should not be started with with SUDO but will request it for a few subcommands.." >&2
+    exit 1
+fi
+
 set -e # Exit on error
 
 # Define directory to save output files
-output_dir="$HOME/.ctee/"
+output_dir=$HOME/.ctee/
+script_dir=$(dirname "$0")
 
 # Function to cleanup temp files
 function cleanup {
-  rm -f "$temp_zshrc"
-  rm -rf "$temp_zsh_dir"
-}
-
-# Function to delete old ctee sessions
-function delete_old_sessions {
-  # If the output directory doesn't exist, no need to clean up
-  if [[ ! -d "$output_dir" ]]; then
-    return 0
-  fi
-  
-  # Use find to delete files in output_dir that were last modified more than 7 days ago
-  find "$output_dir" -type f -mtime +7 ! -exec fuser -s {} \; -exec rm {} \;
-}
-
-# Function to remove strange byte sequences
-function remove_strange_bytes {
-  # The tr command below deletes non-printable characters. 
-  # Note that this includes newlines, so they're added back with the -c option.
-  tr -cd '\11\12\15\40-\176' < "$1" > "${1}_clean"
-  mv "${1}_clean" "$1"
+  rm -f "$temp_bashrc"
 }
 
 # Register the cleanup function to be called on the EXIT signal
@@ -40,9 +27,9 @@ if [ -z "$1" ]
 then
     filename="cli_record_$timestamp"
 else
-    filename="$1"
-    if [ -f "${output_dir}${filename}" ]; then
-        echo "Error: File ${output_dir}${filename} already exists."
+    filename=$1
+    if [ -f "$output_dir$filename" ]; then
+        echo "Error: File $output_dir$filename already exists."
         exit 1
     fi
 fi
@@ -54,22 +41,22 @@ then
     exit 1
 fi
 
-# Create a temporary directory and zshrc file in it
-temp_zsh_dir=$(mktemp -d)
-temp_zshrc="$temp_zsh_dir/.zshrc"
-cat "$output_dir"etc/zshrc.ctee >> $temp_zshrc
+# Create a temporary bashrc file
+temp_bashrc=$(mktemp)
+
+# Define the commands to stop recording and change the prompt
+# echo "PS1='CTEE [REC] \$ '" >> "$temp_bashrc"
+# echo "alias stop_recording='echo Recording Ended; exit'" >> "$temp_bashrc"
+
+# Add optional alias for cspeakes_enumerator. Not default installed, but works if so.
+# echo "alias target=\"/usr/local/bin/create_target.sh\"" >> "$temp_bashrc"
+cat $HOME/.ctee/etc/bashrc.ctee >> "$temp_bashrc"
 
 # Create the target directory if it doesn't already exist
-mkdir -p "$output_dir"
+mkdir -p $output_dir
 
 # Start recording with the 'script' command
-ZDOTDIR="$temp_zsh_dir" script -a "${output_dir}${filename}" -q --command="zsh"
+# The --rcfile option ensures the temporary bashrc file is loaded
+script -a "$output_dir$filename" -q --command="bash --rcfile $temp_bashrc"
 
-# Remove strange bytes
-remove_strange_bytes "${output_dir}${filename}"
-
-# Delete old sessions
-delete_old_sessions
-
-echo "Recording saved in ${output_dir}${filename}"
-
+echo "Recording saved in $output_dir$filename"
